# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-28 19:05
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.utils.timezone
import model_utils.fields
import tinymce.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PetModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('Name', models.CharField(max_length=200, verbose_name="Nom de l'animal")),
                ('Description', tinymce.models.HTMLField(blank=True, null=True, verbose_name='Description')),
                ('Sex', models.CharField(choices=[('M', 'Mâle'), ('F', 'Femelle')], default='M', max_length=30)),
                ('BirthDt', models.DateField(default=datetime.date.today, verbose_name='Date de naissance')),
                ('City', models.CharField(max_length=100, verbose_name='Ville')),
                ('Département', models.CharField(max_length=3, verbose_name='Département')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
