# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-28 19:13
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Pet', '0002_petmodel_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='petmodel',
            old_name='Département',
            new_name='Departement',
        ),
    ]
