# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-28 19:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Pet', '0003_auto_20170728_2113'),
    ]

    operations = [
        migrations.AddField(
            model_name='petmodel',
            name='OK_CHAT',
            field=models.CharField(choices=[('Y', 'Oui'), ('N', 'Non'), ('U', 'Je ne sais pas')], default='U', max_length=1, verbose_name='OK Chat ?'),
        ),
        migrations.AddField(
            model_name='petmodel',
            name='OK_CHIEN',
            field=models.CharField(choices=[('Y', 'Oui'), ('N', 'Non'), ('U', 'Je ne sais pas')], default='U', max_length=1, verbose_name='OK Chien ?'),
        ),
        migrations.AddField(
            model_name='petmodel',
            name='OK_ENFANT',
            field=models.CharField(choices=[('Y', 'Oui'), ('N', 'Non'), ('U', 'Je ne sais pas')], default='U', max_length=1, verbose_name='OK Enfants ?'),
        ),
        migrations.AlterField(
            model_name='petmodel',
            name='Sex',
            field=models.CharField(choices=[('M', 'Mâle'), ('F', 'Femelle')], default='M', max_length=30, verbose_name='Sexe'),
        ),
    ]
