# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-28 21:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Pet', '0004_auto_20170728_2118'),
    ]

    operations = [
        migrations.AddField(
            model_name='petmodel',
            name='Category',
            field=models.CharField(choices=[('Chien', 'Chien'), ('Chat', 'Chat')], default='Chat', max_length=30, verbose_name='Catégorie'),
        ),
    ]
