# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-29 08:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import filer.fields.image


class Migration(migrations.Migration):

    dependencies = [
        ('Pet', '0006_petimagemodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='petimagemodel',
            name='height',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='petimagemodel',
            name='width',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='petimagemodel',
            name='Image',
            field=filer.fields.image.FilerImageField(on_delete=django.db.models.deletion.CASCADE, related_name='product_image', to='filer.Image'),
        ),
    ]
