# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-13 08:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Pet', '0010_auto_20170802_2005'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fa',
            name='TailleMaison',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name="Taille de l'habitation en m²"),
        ),
        migrations.AlterField(
            model_name='fa',
            name='TypeMaison',
            field=models.CharField(choices=[('Maison', 'Maison'), ('Appartement', 'Appartement')], default='Maison', max_length=30, verbose_name='Type habitation'),
        ),
    ]
