# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-13 10:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Pet', '0011_auto_20170813_1036'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='fa',
            options={'verbose_name': "Famille d'accueil", 'verbose_name_plural': "Familles d'accueil"},
        ),
        migrations.AlterModelOptions(
            name='petmodel',
            options={'verbose_name': 'Animal', 'verbose_name_plural': 'Animaux'},
        ),
        migrations.AlterField(
            model_name='petimagemodel',
            name='Pet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Photos', to='Pet.PetModel', verbose_name='Animal'),
        ),
    ]
