# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-13 10:08
from __future__ import unicode_literals

from django.db import migrations
import django.db.models.deletion
import filer.fields.image


class Migration(migrations.Migration):

    dependencies = [
        ('Pet', '0012_auto_20170813_1207'),
    ]

    operations = [
        migrations.AlterField(
            model_name='petimagemodel',
            name='Image',
            field=filer.fields.image.FilerImageField(on_delete=django.db.models.deletion.CASCADE, to='filer.Image'),
        ),
    ]
