# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-15 17:54
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Pet', '0014_auto_20170813_1218'),
    ]

    operations = [
        migrations.RenameField(
            model_name='petmodel',
            old_name='Name',
            new_name='PetName',
        ),
    ]
